### ISSUE TITLE
Export frame time

### ISSUE THREAD

**Issue by gemlongman** [eherr/anim_utils_scripts#1]
https://github.com/eherr/anim_utils_scripts/blob/8668a14fec58d927f0fc00c9e6bd101704701397/run_retargeting.py#L60

target_motion.frame_time = src_motion.frame_time here

but export use target skeleton.frame_time, shouldn't it be self.frame_time?

https://github.com/eherr/anim_utils/blob/7528cc64c94c765084530d8b7673b1caf549fc60/animation_data/motion_vector.py#L168

**Comment by eherr** [comment]
Yes you are right. I have fixed that in the latest commit. Thank you for finding the issue!

**Comment by gemlongman** [comment]
Great~
